<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>

        <!-- Packaging -->
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>

        <!-- Dependencies -->
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>14</LangVersion>

        <!-- Flags -->
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <WarningsAsErrors>Nullable</WarningsAsErrors>

        <!-- Security -->
        <!-- CET compatibility MUST be disabled to allow building and running with Synthesis. -->
        <CETCompat>false</CETCompat>

        <!-- Code -->
        <RootNamespace/>

    </PropertyGroup>

    <ItemGroup>
        <Using Include="System.Diagnostics.CodeAnalysis"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Mutagen.Bethesda.FormKeys.SkyrimSE" Version="3.4.0"/>
        <PackageReference Include="Mutagen.Bethesda.Skyrim" Version="0.54.2"/>
        <PackageReference Include="Mutagen.Bethesda.Synthesis" Version="0.36.5"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Lookups.cs">
            <DependentUpon>Patcher.cs</DependentUpon>
        </Compile>
        <Compile Update="SoulGemPatcher.cs">
            <DependentUpon>Patcher.cs</DependentUpon>
        </Compile>
        <Compile Update="StaffPatcher.cs">
            <DependentUpon>Patcher.cs</DependentUpon>
        </Compile>
        <Compile Update="StaffEnchantmentPatcher.cs">
            <DependentUpon>StaffPatcher.cs</DependentUpon>
        </Compile>
        <Compile Update="StaffRecipePatcher.cs">
            <DependentUpon>StaffPatcher.cs</DependentUpon>
        </Compile>
        <Compile Update="ScrollPatcher.cs">
            <DependentUpon>Patcher.cs</DependentUpon>
        </Compile>
        <Compile Update="ScrollRecipePatcher.cs">
            <DependentUpon>ScrollPatcher.cs</DependentUpon>
        </Compile>
    </ItemGroup>

</Project>
